version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes: 
      - $PWD:/var/www/html
  db:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: rapulu
      MYSQL_PASSWORD: rapulu
    volumes: 
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes: 
  mysql_data: